[[main]]
  name = "Articles"
  pageRef = "articles"
  weight = 10

# [[main]]
#   name = "Travelling"
#   pageRef = "places"
#   weight = 20

[[main]]
  name = "About"
  pageRef = "about"
  weight = 30
